### ISSUE TITLE
WH46, GW1200A, and contributing

### ISSUE THREAD

**Issue by jeffcybulski** [rhockenbury/homebridge-ecowitt-weather-sensors#15]
Ryler, I'm working on setting up a local development environment so I could contribute to this project. 

My first goal is to add the WH46 CO2 Sensor and the GW1200A Gateway. Could you confirm if this is correct? 

1. duplicate WH41.ts as WH46.ts and modify/add data fields
2. duplicate GW1100.ts as GW1200.ts and modify/add data fields
3. modify EcowittPlatform.js

```
Data report: {
  "PASSKEY": "",
  "stationtype": "GW1200A_V1.3.2",
  "runtime": "",
  "heap": "",
  "dateutc": "",
  "tempinf": "88.34",
  "humidityin": "82",
  "baromrelin": "29.864",
  "baromabsin": "29.864",
  "tf_co2": "90.68",
  "humi_co2": "75",
  "pm1_co2": "10.8",
  "pm1_24h_co2": "15.8",
  "pm4_co2": "11.6",
  "pm4_24h_co2": "17.1",
  "pm25_co2": "11.5",
  "pm25_24h_co2": "16.9",
  "pm10_co2": "11.7",
  "pm10_24h_co2": "17.2",
  "co2": "675",
  "co2_24h": "898",
  "co2_batt": "6",
  "freq": "",
  "model": "GW1200A",
  "interval": ""
}
```

**Comment by rhockenbury** [comment]
Hi @jeffcybulski - thanks for reaching out.  First a general note, I'm wrapping up a large refactor (v2) and should have a beta out within the next 1-2 weeks.  My general plan was to get the v2 release out, and then focus on expanding the set of supported sensors.  My recommendation would be to wait until I have a public v2 release, then build from there (rather than using the latest v1 as the starting point).  That said, if you needed something sooner, and did want to contribute GW1200 and WH46 to v1, I would certainly welcome it.  v2 at this point has support for GW1200, but not WH46. 

Getting to your questions, that all looks to be the right approach.  Thanks for sharing the data report.

**Comment by jeffcybulski** [comment]
Thanks for continuing your work. I will wait for v2 before submitting any PRs.

Are you only adding devices that you can test? Else, is it possible to add the WH46 based on these data fields? (I can test it)

**Comment by rhockenbury** [comment]
Hi @jeffcybulski.  The data report (like the one you provided) is typically sufficient for adding support for new sensors.  This plugin processes data reports sent from a base station, and so having the data report is really all that's needed for implementation (the data report is effectively the API between this plugin and the gateway).  Testing with the actual sensors is still super valuable though, and since I don't have a WH46, any testing assistance you can provide would be greatly appreciated.

**Comment by jeffcybulski** [comment]
@rhockenbury In addition to the WH46, here is the data for the WH51L (which looks identical to the WH51). If you could add these 2 devices to v2.0, great. Else, I'm happy to contribute! I'm also considering developing a plugin for the AC Infinity line since their API is relatively mature.

```
Data report: {
  "PASSKEY": "",
  "stationtype": "",
  "runtime": "",
  "heap": "",
  "dateutc": "",
  "soilmoisture5": "58",
  "soilad5": "242",
  "soilmoisture6": "56",
  "soilad6": "232",
  "soilmoisture7": "56",
  "soilad7": "234",
  "soilbatt5": "1.4",
  "soilbatt6": "1.4",
  "soilbatt7": "1.5",
  "co2_batt": "6",
  "freq": "",
  "model": "",
  "interval": ""
}
```

**Comment by rhockenbury** [comment]
Sounds good.  The WH51L is already supported, but I'll put something in the readme to make sure it's clear which variants of which sensors are supported.  Thanks.

**Comment by rhockenbury** [comment]
Hi @jeffcybulski.  Please give the v2.2.0-beta a try.  This version supports WH46, WH51L, and GW1200.  Please let me know if you have any feedback.  Note that I did not implement PM1.0 and PM4.0 for the WH46 as those characteristics are not supported through Homekit at this time (only PM2.5 and PM10 are available).  Let me know how important you feel that displaying PM1.0 and PM4.0 data is as we could potentially implement them through custom characteristics.

**Comment by jeffcybulski** [comment]
Wow! You really did some work. Thank you very much.

QQ: How can I get the JSON logs for each team a report is made from the gateway? I see that's no longer being logged.

**Comment by rhockenbury** [comment]
Hi @jeffcybulski.  The data report is logged at a debug level, which isn't shown in the Homebridge logs by default.  I have [written instructions here](https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors/wiki/Submitting-Data-Report) for obtaining the data report, which boils down to enabling debug mode and restarting Homebridge.
