### ISSUE TITLE
WN31 Name Override Help 

### ISSUE THREAD

**Issue by anthonyb82** [rhockenbury/homebridge-ecowitt-weather-sensors#39]
Hi there! I have 4 WN31 sensors to measure temp/humidity. I am having no luck configuring the Name Overrides to get them to represent where they belong. I have tried a number of options after reading the wiki, such as: 

WN31CH1:humidity
WN31CH1:humdity
WN31CH1:indoorhumidity
WN31CH1:indoorhumdity
WN31CH1:humidity1
WN31CH1:extrahumid1

I even tried just changing the overall WN31CH1 to reflect the name I want. They always just appear in my HomeKit as "Temperature" or "Humidity" with the differentiating name not showing up. I'm certain I am doing something wrong, but I'm at a loss! Could you please share specifically what I should be entering for the sensor ID? Thank you so much!

**Comment by rhockenbury** [comment]
Hi @anthonyb82.  Thanks for reaching out.  Apologize for any confusion about the name overrides. 

It should be `WN31CH1:humidity`.  It happens [right here in the code ](https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors/blob/master/src/devices/WN31.ts#L41) and [gets tested here](https://github.com/rhockenbury/homebridge-ecowitt-weather-sensors/blob/master/tests/unit/devices/WN31.spec.ts#L54). 

Can you modify your config to use `WN31CH1:humidity`, save the config, restart homebridge, wait for a data report to be received, then check if the name is updated?  It's important to wait for the data report after the restart because the name will only be updated when a data report is received. 

If that doesn't work, then I would like to request that you (1) send me your json config for the plugin, and (2) put homebridge into debug mode, and send me the startup logs for the plugin.  Those two things should enable me to debug further.

**Comment by anthonyb82** [comment]
Thank you so much! I got things figured out- I know I tried what you put above, but for whatever reason it didn't take. I copy and pasted from your response though and that seemed to work right away. I appreciate you getting back to me. I really like this plug-in (coming from a different/older version) and this improves a few things that always irked me. For whatever reason, I needed up spending way to much time on this particular part- knew it had to be user error, but I was out of ideas to try by that point. 

Again, thanks for the help!
